apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
 ports:
   - port: 80
    nodePort: 30040
 selector:
   app: owncloud
   tier: frontend
 type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: oc-pvc
 labels:
   app: owncloud
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
    storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
       app: owncloud
       tier: frontend
 strategy:
     type: Recreate
 template:
   metadata:
     labels:
      app: owncloud
      tier: frontend
  spec:
   containers:
     - image: owncloud:latest
       name: owncloud
       env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                name: mysql-passwd
                key: password
         - name: MYSQL_USER
           value: Sappy
         - name: MYSQL_PASSWORD
           valueFrom:
               secretKeyRef:
                 name: mysqluser-passwd
                 key: usrpasswd
        - name: MYSQL_DATABASE
          value: mydb
        ports:
         - containerPort: 80
        name: owncloud
       volumeMounts:
         - name: oc-pv
          mountPath: /var/www/html
  volumes:
    - name: oc-pv
      persistentVolumeClaim:
           claimName: oc-pvc